import { AgentPlan, AgentToolCall, MAX_AGENT_PLAN_STEPS } from "../../orchestrator/types";

/**
 * Shared AI Plan & Tool Selection Validator (Phase 3.3 - Step 4.8)
 *
 * Validates candidate AgentPlans generated by any AI Provider model before execution.
 *
 * SECURITY & VALIDATION BOUNDARY:
 * 1. Tool Whitelisting: Rejects unknown tools not registered in ALFRED.
 * 2. Input Sanitization: Rejects shell metacharacters and path traversal attempts in arguments.
 * 3. Argument Validation: Enforces object arguments and validates tool parameter shapes.
 * 4. Ordering Preservation: Maintains exact sequence of valid tool calls for multi-step plans.
 */

export interface ValidationResult {
    valid: boolean;
    plan?: AgentPlan;
    error?: string;
    rejectedCallsCount: number;
}

/** Whitelisted tool names supported by ALFRED ToolRegistry */
export const ALLOWED_TOOL_NAMES = new Set([
    "launch_application",
    "navigate",
    "system_status",
    "start_deep_work",
    "launch_workspace",
    "show_tasks",
    "open_url",
    "open_path",
    "create_task",
    "complete_task",
    "create_goal",
    "update_goal",
    "update_project",
]);

/** Shell metacharacters regex for parameter security checks */
const DANGEROUS_SHELL_REGEX = /[;&|`$()<>{}\n\r]/;

/** Path traversal regex */
const PATH_TRAVERSAL_REGEX = /(?:^|[/\\])\.\.(?:[/\\]|$)/;

/**
 * Validates a single candidate tool call object.
 * Returns valid AgentToolCall or null if invalid/rejected.
 */
export function validateToolCall(candidate: unknown): AgentToolCall | null {
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) {
        return null;
    }

    const obj = candidate as Record<string, unknown>;

    // 1. Tool Name Validation
    if (typeof obj.tool !== "string" || !obj.tool.trim()) return null;
    const toolName = obj.tool.trim();

    if (!ALLOWED_TOOL_NAMES.has(toolName)) {
        // Unknown tool — reject to enforce tool boundary
        return null;
    }

    // 2. Arguments Validation
    if (!obj.arguments || typeof obj.arguments !== "object" || Array.isArray(obj.arguments)) {
        return null;
    }

    const args = { ...(obj.arguments as Record<string, unknown>) };

    // 2b. Optional Step Dependency Validation (Phase 4.15)
    let normalizedDependsOn: number[] | undefined;
    if (obj.dependsOn !== undefined) {
        if (!Array.isArray(obj.dependsOn)) {
            return null; // Must be an array
        }
        for (const dep of obj.dependsOn) {
            if (typeof dep !== "number" || !Number.isInteger(dep)) {
                return null; // Must be integer
            }
        }
        // Normalize duplicate dependency indexes deterministically
        normalizedDependsOn = Array.from(new Set(obj.dependsOn as number[])).sort((a, b) => a - b);
    }

    // 3. Security parameter checks based on tool category
    if (toolName === "launch_application") {
        const appName = args.appName || args.application || args.target;
        if (typeof appName !== "string" || !appName.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(appName) || PATH_TRAVERSAL_REGEX.test(appName)) {
            return null;
        }
        args.appName = appName.trim();
    } else if (toolName === "navigate") {
        const target = args.target || args.view || args.targetPath || args.route;
        if (typeof target !== "string" || !target.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(target)) return null;
        args.target = target.trim();
        args.route = target.trim();
    } else if (toolName === "open_url") {
        const url = args.url;
        if (typeof url !== "string" || !url.trim()) return null;
        const lowerUrl = url.trim().toLowerCase();
        if (!lowerUrl.startsWith("http://") && !lowerUrl.startsWith("https://")) {
            return null;
        }
        if (DANGEROUS_SHELL_REGEX.test(url)) return null;
        args.url = url.trim();
    } else if (toolName === "open_path") {
        const pathStr = args.path;
        if (typeof pathStr !== "string" || !pathStr.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(pathStr) || PATH_TRAVERSAL_REGEX.test(pathStr)) {
            return null;
        }
        args.path = pathStr.trim();
    } else if (toolName === "launch_workspace") {
        const wsName = args.workspaceName || args.name || args.workspace;
        if (typeof wsName !== "string" || !wsName.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(wsName)) return null;
        args.workspaceName = wsName.trim();
    } else if (toolName === "create_task") {
        const rawText = args.text ?? args.title;
        if (typeof rawText !== "string" || !rawText.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(rawText)) return null;
        args.text = rawText.trim();
        if (args.category !== undefined && typeof args.category !== "string") return null;
        if (typeof args.category === "string") {
            if (DANGEROUS_SHELL_REGEX.test(args.category)) return null;
            args.category = args.category.trim();
        }
    } else if (toolName === "complete_task") {
        const rawId = args.taskId ?? args.id;
        if (typeof rawId !== "string" && typeof rawId !== "number") return null;
        const idStr = String(rawId).trim();
        if (!idStr || DANGEROUS_SHELL_REGEX.test(idStr)) return null;
        args.taskId = idStr;
    } else if (toolName === "create_goal") {
        // Disallow invented fields
        const allowedGoalFields = new Set(["title", "type", "target"]);
        for (const k of Object.keys(args)) {
            if (!allowedGoalFields.has(k)) return null;
        }
        if (typeof args.title !== "string" || !args.title.trim()) return null;
        if (DANGEROUS_SHELL_REGEX.test(args.title)) return null;
        args.title = args.title.trim();
        if (args.type !== undefined) {
            if (typeof args.type !== "string" || (args.type !== "Weekly" && args.type !== "Monthly")) {
                return null;
            }
        }
        if (args.target !== undefined) {
            if (typeof args.target !== "number" || isNaN(args.target) || !isFinite(args.target) || args.target <= 0) {
                return null;
            }
        }
    } else if (toolName === "update_goal") {
        // Disallow invented fields
        const allowedUpdateGoalFields = new Set(["goalId", "id", "title", "target", "current", "completed"]);
        for (const k of Object.keys(args)) {
            if (!allowedUpdateGoalFields.has(k)) return null;
        }
        const rawId = args.goalId ?? args.id;
        if (typeof rawId !== "string" && typeof rawId !== "number") return null;
        const idStr = String(rawId).trim();
        if (!idStr || DANGEROUS_SHELL_REGEX.test(idStr)) return null;
        args.goalId = idStr;
        if (args.title !== undefined) {
            if (typeof args.title !== "string" || !args.title.trim() || DANGEROUS_SHELL_REGEX.test(args.title)) {
                return null;
            }
            args.title = args.title.trim();
        }
        if (args.target !== undefined) {
            if (typeof args.target !== "number" || isNaN(args.target) || !isFinite(args.target) || args.target <= 0) {
                return null;
            }
        }
        if (args.current !== undefined) {
            if (typeof args.current !== "number" || isNaN(args.current) || !isFinite(args.current) || args.current < 0) {
                return null;
            }
        }
        if (args.completed !== undefined && typeof args.completed !== "boolean") {
            return null;
        }
    } else if (toolName === "update_project") {
        // Disallow invented fields
        const allowedUpdateProjFields = new Set(["projectId", "id", "progress", "status", "name", "description", "category"]);
        for (const k of Object.keys(args)) {
            if (!allowedUpdateProjFields.has(k)) return null;
        }
        const rawId = args.projectId ?? args.id;
        if (typeof rawId !== "string" && typeof rawId !== "number") return null;
        const idStr = String(rawId).trim();
        if (!idStr || DANGEROUS_SHELL_REGEX.test(idStr)) return null;
        args.projectId = idStr;
        if (args.progress !== undefined) {
            if (typeof args.progress !== "number" || isNaN(args.progress) || !isFinite(args.progress) || args.progress < 0 || args.progress > 100) {
                return null;
            }
        }
        if (args.status !== undefined) {
            if (typeof args.status !== "string" || !["Not Started", "In Progress", "Completed"].includes(args.status)) {
                return null;
            }
        }
        if (args.name !== undefined) {
            if (typeof args.name !== "string" || !args.name.trim() || DANGEROUS_SHELL_REGEX.test(args.name)) {
                return null;
            }
            args.name = args.name.trim();
        }
        if (args.description !== undefined) {
            if (typeof args.description !== "string" || DANGEROUS_SHELL_REGEX.test(args.description)) {
                return null;
            }
        }
        if (args.category !== undefined) {
            if (typeof args.category !== "string" || !["DSA", "Data Science", "College", "Hackathon", "Personal"].includes(args.category)) {
                return null;
            }
        }
    }

    const validToolCall: AgentToolCall = {
        tool: toolName,
        arguments: args,
    };
    if (normalizedDependsOn !== undefined) {
        validToolCall.dependsOn = normalizedDependsOn;
    }

    return validToolCall;
}

/**
 * Validates dependency graph of a multi-step plan (Phase 4.15).
 * Enforces:
 * - dependsOn must be an array of previous step indexes.
 * - No self-dependency (step cannot depend on itself).
 * - No future dependency (step cannot depend on future step).
 * - Indexes must be within range [0, totalSteps - 1].
 * - Circular dependencies must be rejected.
 */
export function validatePlanDependencies(toolCalls: unknown[]): { valid: boolean; error?: string } {
    const totalSteps = toolCalls.length;
    const graph = new Map<number, number[]>();

    for (let i = 0; i < totalSteps; i++) {
        const step = toolCalls[i];
        if (!step || typeof step !== "object" || Array.isArray(step)) continue;
        const depCandidate = (step as Record<string, unknown>).dependsOn;
        if (depCandidate === undefined) continue;

        if (!Array.isArray(depCandidate)) {
            return {
                valid: false,
                error: `Step ${i + 1} has invalid 'dependsOn': must be an array of step indexes.`,
            };
        }

        for (const dep of depCandidate) {
            if (typeof dep !== "number" || !Number.isInteger(dep)) {
                return {
                    valid: false,
                    error: `Step ${i + 1} has invalid dependency index: must be an integer.`,
                };
            }
            if (dep < 0 || dep >= totalSteps) {
                return {
                    valid: false,
                    error: `Step ${i + 1} depends on out-of-range step index ${dep}. Plan has ${totalSteps} steps (indexes 0 to ${totalSteps - 1}).`,
                };
            }
            if (dep === i) {
                return {
                    valid: false,
                    error: `Step ${i + 1} (index ${i}) cannot depend on itself.`,
                };
            }
            if (dep > i) {
                return {
                    valid: false,
                    error: `Step ${i + 1} (index ${i}) cannot depend on future step index ${dep}. Dependencies must refer only to earlier steps.`,
                };
            }
        }
        graph.set(i, depCandidate as number[]);
    }

    // Explicit cycle detection check across dependency graph
    const visited = new Set<number>();
    const recStack = new Set<number>();

    function hasCycle(node: number): boolean {
        visited.add(node);
        recStack.add(node);

        const neighbors = graph.get(node) || [];
        for (const neighbor of neighbors) {
            if (!visited.has(neighbor)) {
                if (hasCycle(neighbor)) return true;
            } else if (recStack.has(neighbor)) {
                return true;
            }
        }

        recStack.delete(node);
        return false;
    }

    for (let i = 0; i < totalSteps; i++) {
        if (!visited.has(i)) {
            if (hasCycle(i)) {
                return {
                    valid: false,
                    error: `Circular dependency detected in plan involving step ${i + 1}.`,
                };
            }
        }
    }

    return { valid: true };
}

/**
 * Extracts JSON text from raw model output, handling markdown code fences.
 */
export function extractJsonFromRawText(rawText: string): string | null {
    if (!rawText || !rawText.trim()) return null;

    // Try markdown code fence extraction
    const fencedMatch = rawText.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (fencedMatch) {
        return fencedMatch[1].trim();
    }

    // Try raw JSON object extraction
    const firstBrace = rawText.indexOf("{");
    const lastBrace = rawText.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace > firstBrace) {
        return rawText.slice(firstBrace, lastBrace + 1);
    }

    return null;
}

export interface PlanValidationOptions {
    /** If true, any invalid step in a multi-step plan causes the entire plan to be rejected (Phase 4.14) */
    strict?: boolean;
}

export { MAX_AGENT_PLAN_STEPS };

/**
 * Parses, extracts, and validates an AgentPlan JSON payload from raw LLM output text.
 * Preserves multi-tool call array ordering.
 */
export function parseAndValidateAgentPlan(
    rawText: string,
    userRequest: string,
    options?: PlanValidationOptions
): ValidationResult {
    if (!rawText || !rawText.trim()) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Provider returned an empty response.",
        };
    }

    const jsonStr = extractJsonFromRawText(rawText);
    if (!jsonStr) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Could not extract a valid JSON object from model response. Ensure model outputs JSON.",
        };
    }

    let parsed: unknown;
    try {
        parsed = JSON.parse(jsonStr);
    } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: `JSON parse error in model output: ${msg}`,
        };
    }

    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Parsed model output is not a JSON object.",
        };
    }

    const obj = parsed as Record<string, unknown>;

    // Check for AI Answer Mode response
    const isAnswerType =
        obj.type === "answer" ||
        (typeof obj.answerText === "string" && obj.answerText.trim().length > 0);

    if (isAnswerType) {
        const answerText =
            typeof obj.answerText === "string" && obj.answerText.trim()
                ? obj.answerText.trim()
                : typeof obj.explanation === "string"
                ? obj.explanation.trim()
                : "Informational answer provided.";

        const plan: AgentPlan = {
            userRequest,
            toolCalls: [], // STRICT SECURITY GUARANTEE: Answers NEVER contain tool calls
            explanation: typeof obj.explanation === "string" ? obj.explanation.trim() : answerText,
            type: "answer",
            answerText,
        };

        return {
            valid: true,
            plan,
            rejectedCallsCount: 0,
        };
    }

    if (!Array.isArray(obj.toolCalls)) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Model output is missing required 'toolCalls' array.",
        };
    }

    if (obj.toolCalls.length === 0) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Action plan requires at least one tool call.",
        };
    }

    if (obj.toolCalls.length > MAX_AGENT_PLAN_STEPS) {
        return {
            valid: false,
            rejectedCallsCount: obj.toolCalls.length,
            error: `Plan exceeds maximum allowed steps (${MAX_AGENT_PLAN_STEPS}). Found ${obj.toolCalls.length}.`,
        };
    }

    // Validate step dependencies across the entire plan (Phase 4.15)
    const depValidation = validatePlanDependencies(obj.toolCalls);
    if (!depValidation.valid) {
        return {
            valid: false,
            rejectedCallsCount: obj.toolCalls.length,
            error: `Plan rejected: ${depValidation.error}`,
        };
    }

    const validToolCalls: AgentToolCall[] = [];
    let rejectedCallsCount = 0;

    for (let i = 0; i < obj.toolCalls.length; i++) {
        const candidate = obj.toolCalls[i];
        const validated = validateToolCall(candidate);
        if (validated) {
            validToolCalls.push(validated);
        } else {
            rejectedCallsCount++;
            if (options?.strict) {
                const toolName =
                    candidate && typeof candidate === "object" && "tool" in candidate
                        ? String((candidate as Record<string, unknown>).tool)
                        : "unknown";
                return {
                    valid: false,
                    rejectedCallsCount,
                    error: `Plan rejected: step ${i + 1} (${toolName}) is invalid, unknown, or contains disallowed arguments.`,
                };
            }
        }
    }

    if (validToolCalls.length === 0 && options?.strict) {
        const errorMsg = "All candidate tool calls were rejected: unknown tool names or invalid arguments.";
        return {
            valid: false,
            plan: {
                userRequest,
                toolCalls: [],
                explanation: errorMsg,
                type: "action",
            },
            rejectedCallsCount,
            error: errorMsg,
        };
    }

    let explanation =
        typeof obj.explanation === "string" && obj.explanation.trim()
            ? obj.explanation.trim()
            : "Plan generated by AI provider.";

    if (rejectedCallsCount > 0) {
        explanation += ` (${rejectedCallsCount} tool call(s) rejected: unknown tool name or invalid arguments.)`;
    }

    const plan: AgentPlan = {
        userRequest,
        toolCalls: validToolCalls,
        explanation,
        type: "action",
    };

    return {
        valid: true,
        plan,
        rejectedCallsCount,
    };
}

/**
 * Directly validates an AgentPlan object or candidate plan object before execution (Phase 4.14).
 * Defaults to strict validation where any invalid step rejects the entire plan.
 */
export function validateAgentPlan(
    candidate: unknown,
    options: PlanValidationOptions = { strict: true }
): ValidationResult {
    if (typeof candidate === "string") {
        return parseAndValidateAgentPlan(candidate, "Validate Plan", options);
    }
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) {
        return {
            valid: false,
            rejectedCallsCount: 0,
            error: "Candidate plan must be a non-null object.",
        };
    }
    const userReq =
        "userRequest" in candidate && typeof (candidate as any).userRequest === "string"
            ? (candidate as any).userRequest
            : "Validate Plan";
    return parseAndValidateAgentPlan(JSON.stringify(candidate), userReq, options);
}
